version: '3.8'

services:
  nestjs-app:
    image: node:20
    command: sh -c 'npm install && npm run start:dev'
    volumes:
    #  Docker Compose 所在的目錄
      - ./:/usr/src/app
    # 容器的工作目錄
    working_dir: /usr/src/app
    ports:
      - '3000:3000'
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: user
      DB_PASSWORD: 123456
      DB_NAME: ecPay
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=ecPay
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456
    ports:
      - '5432:5432'
    # docker中一種數據持久化的方式，即使容器重啟或刪除，存在資料卷中的資料也不會消失。
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
